# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reaching Inside
email: w.emerson.michaels@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Part Recovery, part Journey, this is where I am.
baseurl: "/reachinginside/"
url: "http://localhost:4000"

# Build settings
markdown: rdiscount
rdiscount:
 extensions: [smart]
permalink: /articles/:title
# paginate: 3
